# frontend-routing.yaml: Frontend Application (frontend-ns) 및 Istio Gateway/VirtualService

# 1. 네임스페이스
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns
  labels:
    istio-injection: enabled # Istio 활성화 필수
---
# 4. ConfigMaps (Frontend)
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend-ns
data:
  # Node.js 서버의 SSR 데이터 패치용 내부 DNS 주소 (클라이언트용은 /api로 별도 처리)
  GUESTBOOK_API_ADDR: "http://backend-svc.backend-ns.svc.cluster.local:8000"
---
# 7. Services (Frontend)
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: frontend-ns
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
# 9. Deployments (Frontend)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: frontend
        image: harbor.local.net/haniplog/haniplog-frontend:v1.47

        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: GUESTBOOK_API_ADDR
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: GUESTBOOK_API_ADDR
---
# 11. Istio Gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: book-gateway
  namespace: frontend-ns
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# 12. Istio VirtualService (라우팅 규칙)
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: book-vs
  namespace: frontend-ns
spec:
  hosts:
  - "*"
  gateways:
  - book-gateway
  http:




  # [1] API 요청: /api/ 경로로 오는 요청은 백엔드로 전달
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: backend-svc.backend-ns.svc.cluster.local
        port:
          number: 8000

  # [2] 페이지 요청: 나머지 모든 요청(웹페이지)은 프론트엔드로 전달
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend-svc.frontend-ns.svc.cluster.local
        port:
          number: 8000
