# db.yaml (인증 관련 설정 모두 제거)

# 1. 네임스페이스
apiVersion: v1
kind: Namespace
metadata:
  name: db-ns
---
# 2. Keyfile Secret 제거됨
# 3. 최고 관리자 계정 Secret 제거됨

# 4. Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: db-ns
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: db
---
# 5. MongoDB StatefulSet (인증 관련 옵션 및 env 변수 제거 + hostPath)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: db-ns
spec:
  serviceName: "mongo-svc"
  replicas: 1 # hostPath 사용
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mongo:8
          ports:
            - containerPort: 27017
          command:
            - "mongod"
            - "--replSet"
            - "rs0"
            # --keyFile 및 --auth 옵션 제거
            - "--bind_ip_all"
          # env: MONGO_INITDB_ROOT_USERNAME/PASSWORD 환경 변수 블록 전체 제거
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            # mongo-keyfile-volume mount 제거
      
      volumes:
        - name: mongo-data
          hostPath:
            path: /mnt/data/mongodb-data 
            type: DirectoryOrCreate
        # mongo-keyfile-volume 정의 제거
---
# 6. MongoDB 자동 초기화 Job (추가됨)
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init-job
  namespace: db-ns
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:8
        command:
        - bash
        - -c
        - |
          echo "Waiting for MongoDB to be ready..."
          # 1. MongoDB 접속 가능할 때까지 대기
          until mongosh --host mongodb-0.mongo-svc.db-ns.svc.cluster.local:27017 --eval "print(\"waited for connection\")"; do sleep 2; done
          
          echo "Initializing Replica Set..."
          # 2. rs.initiate() 실행 (이미 초기화된 경우 에러 무시)
          mongosh --host mongodb-0.mongo-svc.db-ns.svc.cluster.local:27017 --eval '
            try {
              rs.initiate({
                _id: "rs0",
                members: [{ _id: 0, host: "mongodb-0.mongo-svc.db-ns.svc.cluster.local:27017" }]
              });
              print("Replica Set initialized successfully.");
            } catch (e) {
              if (e.codeName === "AlreadyInitialized") {
                print("Replica Set is already initialized.");
              } else {
                throw e;
              }
            }
          '
      restartPolicy: OnFailure
