# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend-ns
data:
  GUESTBOOK_API_ADDR: "http://backend-external-svc.frontend-ns.svc.cluster.local:8000"
---
# Service (Frontend)
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: frontend-ns
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
# Service (Backend ExternalName -> frontend-ns에서 backend-ns를 바라보기 위함)
apiVersion: v1
kind: Service
metadata:
  name: backend-external-svc
  namespace: frontend-ns
spec:
  type: ExternalName
  externalName: backend-svc.backend-ns.svc.cluster.local
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: frontend-ns
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend-external-svc
              port:
                number: 8000
        - path: /register
          pathType: Exact
          backend:
            service:
              name: backend-external-svc
              port:
                number: 8000
        - path: /login
          pathType: Exact
          backend:
            service:
              name: backend-external-svc
              port:
                number: 8000
        - path: /reviews
          pathType: Exact
          backend:
            service:
              name: backend-external-svc
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-svc
              port:
                number: 8000